---------------------- [[ Transport ]] -----------------------
data.raw.item["transport-belt"].subgroup = "dytech-belt"
data.raw.item["transport-belt"].order = "1"
data.raw.item["fast-transport-belt"].subgroup = "dytech-belt"
data.raw.item["fast-transport-belt"].order = "2"
data.raw.item["express-transport-belt"].subgroup = "dytech-belt"
data.raw.item["express-transport-belt"].order = "3"
data.raw.item["underground-belt"].subgroup = "dytech-underground"
data.raw.item["underground-belt"].order = "1"
data.raw.item["fast-underground-belt"].subgroup = "dytech-underground"
data.raw.item["fast-underground-belt"].order = "2"
data.raw.item["express-underground-belt"].subgroup = "dytech-underground"
data.raw.item["express-underground-belt"].order = "3"
data.raw.item["splitter"].subgroup = "dytech-splitter"
data.raw.item["splitter"].order = "1"
data.raw.item["fast-splitter"].subgroup = "dytech-splitter"
data.raw.item["fast-splitter"].order = "2"
data.raw.item["express-splitter"].subgroup = "dytech-splitter"
data.raw.item["express-splitter"].order = "3"
data.raw.item["pipe"].subgroup = "dytech-pipe"
data.raw.item["pipe"].order = "1"
data.raw.item["pipe-to-ground"].subgroup = "dytech-pipe-ground"
data.raw.item["pipe-to-ground"].order = "1"
data.raw.item["storage-tank"].subgroup = "dytech-storage-tank"
data.raw.item["storage-tank"].order = "1"
data.raw.item["small-pump"].subgroup = "dytech-pump"
data.raw.item["small-pump"].order = "1"


if data.raw.item["super-transport-belt"] then
	data.raw.item["super-transport-belt"].subgroup = "dytech-belt"
	data.raw.item["super-transport-belt"].order = "4"
	data.raw.item["extreme-transport-belt"].subgroup = "dytech-belt"
	data.raw.item["extreme-transport-belt"].order = "5"
	data.raw.item["super-transport-belt-to-ground"].subgroup = "dytech-underground"
	data.raw.item["super-transport-belt-to-ground"].order = "4"
	data.raw.item["extreme-transport-belt-to-ground"].subgroup = "dytech-underground"
	data.raw.item["extreme-transport-belt-to-ground"].order = "5"
	data.raw.item["super-splitter"].subgroup = "dytech-splitter"
	data.raw.item["super-splitter"].order = "4"
	data.raw.item["extreme-splitter"].subgroup = "dytech-splitter"
	data.raw.item["extreme-splitter"].order = "5"
end
if data.raw.item["pipe-mk2"] then
	data.raw.item["pipe-mk2"].subgroup = "dytech-pipe"
	data.raw.item["pipe-mk2"].order = "2"
	data.raw.item["pipe-mk3"].subgroup = "dytech-pipe"
	data.raw.item["pipe-mk3"].order = "3"
	data.raw.item["pipe-mk4"].subgroup = "dytech-pipe"
	data.raw.item["pipe-mk4"].order = "4"
	data.raw.item["pipe-mk5"].subgroup = "dytech-pipe"
	data.raw.item["pipe-mk5"].order = "5"
	data.raw.item["pipe-to-ground-mk2"].subgroup = "dytech-pipe-ground"
	data.raw.item["pipe-to-ground-mk2"].order = "2"
	data.raw.item["pipe-to-ground-mk3"].subgroup = "dytech-pipe-ground"
	data.raw.item["pipe-to-ground-mk3"].order = "3"
	data.raw.item["pipe-to-ground-mk4"].subgroup = "dytech-pipe-ground"
	data.raw.item["pipe-to-ground-mk4"].order = "4"
	data.raw.item["pipe-to-ground-mk5"].subgroup = "dytech-pipe-ground"
	data.raw.item["pipe-to-ground-mk5"].order = "5"
end
if data.raw.item["small-pump-mk2"] then
	data.raw.item["small-pump-mk2"].subgroup = "dytech-pump"
	data.raw.item["small-pump-mk2"].order = "2"
	data.raw.item["small-pump-mk3"].subgroup = "dytech-pump"
	data.raw.item["small-pump-mk3"].order = "3"
	data.raw.item["small-pump-mk4"].subgroup = "dytech-pump"
	data.raw.item["small-pump-mk4"].order = "4"
	data.raw.item["small-pump-mk5"].subgroup = "dytech-pump"
	data.raw.item["small-pump-mk5"].order = "5"
end
if data.raw.item["storage-tank-2"] then
	data.raw.item["storage-tank-2"].subgroup = "dytech-storage-tank"
	data.raw.item["storage-tank-2"].order = "2"
	data.raw.item["storage-tank-3"].subgroup = "dytech-storage-tank"
	data.raw.item["storage-tank-3"].order = "3"
	data.raw.item["storage-tank-4"].subgroup = "dytech-storage-tank"
	data.raw.item["storage-tank-4"].order = "4"
	data.raw.item["storage-tank-5"].subgroup = "dytech-storage-tank"
	data.raw.item["storage-tank-5"].order = "5"
end

---------------------------------[[ Chests ]] ------------------

data.raw.item["wooden-chest"].subgroup = "inserters-dytech-chest"
data.raw.item["wooden-chest"].order = "1"
data.raw.item["iron-chest"].subgroup = "inserters-dytech-chest"
data.raw.item["iron-chest"].order = "2"
data.raw.item["steel-chest"].subgroup = "inserters-dytech-chest"
data.raw.item["steel-chest"].order = "3"
if data.raw.item["wooden-chest-medium"] then
	data.raw.item["wooden-chest-medium"].subgroup = "inserters-dytech-chest-medium"
	data.raw.item["wooden-chest-medium"].order = "1"
	data.raw.item["iron-chest-medium"].subgroup = "inserters-dytech-chest-medium"
	data.raw.item["iron-chest-medium"].order = "2"
	data.raw.item["steel-chest-medium"].subgroup = "inserters-dytech-chest-medium"
	data.raw.item["steel-chest-medium"].order = "3"
	data.raw.item["wooden-chest-big"].subgroup = "inserters-dytech-chest-big"
	data.raw.item["wooden-chest-big"].order = "1"
	data.raw.item["iron-chest-big"].subgroup = "inserters-dytech-chest-big"
	data.raw.item["iron-chest-big"].order = "2"
	data.raw.item["steel-chest-big"].subgroup = "inserters-dytech-chest-big"
	data.raw.item["steel-chest-big"].order = "3"
end
if data.raw.item["item-collector-area"] then
	data.raw.item["item-collector-area"].subgroup = "inserters-other"
	data.raw.item["item-collector-area"].order = "1"
end
---------------------------------[[ Logistic ]]----------------------------------

data.raw.blueprint["blueprint"].subgroup = "dytech-planner"
data.raw.blueprint["blueprint"].order = "1"
data.raw["blueprint-book"]["blueprint-book"].subgroup = "dytech-planner"
data.raw["blueprint-book"]["blueprint-book"].order = "11"
data.raw["deconstruction-item"]["deconstruction-planner"].subgroup = "dytech-planner"
data.raw["deconstruction-item"]["deconstruction-planner"].order = "2"
data.raw.item["roboport"].subgroup = "dytech-roboports"
data.raw.item["roboport"].order = "1"
data.raw.item["logistic-robot"].subgroup = "dytech-logistic"
data.raw.item["logistic-robot"].order = "1"
data.raw.item["construction-robot"].subgroup = "dytech-construction"
data.raw.item["construction-robot"].order = "1"
data.raw.item["logistic-chest-passive-provider"].subgroup = "dytech-passive"
data.raw.item["logistic-chest-passive-provider"].order = "1"
data.raw.item["logistic-chest-active-provider"].subgroup = "dytech-active"
data.raw.item["logistic-chest-active-provider"].order = "1"
data.raw.item["logistic-chest-storage"].subgroup = "dytech-storage"
data.raw.item["logistic-chest-storage"].order = "1"
data.raw.item["logistic-chest-requester"].subgroup = "dytech-request"
data.raw.item["logistic-chest-requester"].order = "1"
data.raw.item["arithmetic-combinator"].subgroup = "dytech-combinators"
data.raw.item["arithmetic-combinator"].order = "1"
data.raw.item["decider-combinator"].subgroup = "dytech-combinators"
data.raw.item["decider-combinator"].order = "2"
data.raw.item["constant-combinator"].subgroup = "dytech-combinators"
data.raw.item["constant-combinator"].order = "3"
data.raw.item["power-switch"].subgroup = "dytech-combinators"
data.raw.item["power-switch"].order = "4"
data.raw["repair-tool"]["repair-pack"].subgroup = "dytech-repair-pack"
data.raw["repair-tool"]["repair-pack"].order = "2"

if data.raw["deconstruction-item"]["upgrade-planner"] then
	data.raw["deconstruction-item"]["upgrade-planner"].subgroup = "dytech-planner"
	data.raw["deconstruction-item"]["upgrade-planner"].order = "3"
end
if data.raw["repair-tool"]["repair-pack-0"] then
	data.raw["repair-tool"]["repair-pack-0"].subgroup = "dytech-repair-pack"
	data.raw["repair-tool"]["repair-pack-0"].order = "1"
	data.raw["repair-tool"]["repair-pack-2"].subgroup = "dytech-repair-pack"
	data.raw["repair-tool"]["repair-pack-2"].order = "3"
	data.raw["repair-tool"]["repair-pack-3"].subgroup = "dytech-repair-pack"
	data.raw["repair-tool"]["repair-pack-3"].order = "4"
end
if data.raw.item["roboport-1"] then
	data.raw.item["roboport-1"].subgroup = "dytech-roboports"
	data.raw.item["roboport-1"].order = "2"
	data.raw.item["roboport-2"].subgroup = "dytech-roboports"
	data.raw.item["roboport-2"].order = "3"
	data.raw.item["robot-charger-1"].subgroup = "dytech-charger"
	data.raw.item["robot-charger-1"].order = "1"
	data.raw.item["robot-charger-2"].subgroup = "dytech-charger"
	data.raw.item["robot-charger-2"].order = "2"
	data.raw.item["logistic-robot-1"].subgroup = "dytech-logistic"
	data.raw.item["logistic-robot-1"].order = "2"
	data.raw.item["logistic-robot-2"].subgroup = "dytech-logistic"
	data.raw.item["logistic-robot-2"].order = "3"
	data.raw.item["construction-robot-1"].subgroup = "dytech-construction"
	data.raw.item["construction-robot-1"].order = "2"
	data.raw.item["construction-robot-2"].subgroup = "dytech-construction"
	data.raw.item["construction-robot-2"].order = "3"
	data.raw.item["logistic-chest-passive-provider-1"].subgroup = "dytech-passive"
	data.raw.item["logistic-chest-passive-provider-1"].order = "2"
	data.raw.item["logistic-chest-passive-provider-2"].subgroup = "dytech-passive"
	data.raw.item["logistic-chest-passive-provider-2"].order = "3"
	data.raw.item["logistic-chest-active-provider-1"].subgroup = "dytech-active"
	data.raw.item["logistic-chest-active-provider-1"].order = "2"
	data.raw.item["logistic-chest-active-provider-2"].subgroup = "dytech-active"
	data.raw.item["logistic-chest-active-provider-2"].order = "3"
	data.raw.item["logistic-chest-storage-1"].subgroup = "dytech-storage"
	data.raw.item["logistic-chest-storage-1"].order = "2"
	data.raw.item["logistic-chest-storage-2"].subgroup = "dytech-storage"
	data.raw.item["logistic-chest-storage-2"].order = "3"
	data.raw.item["logistic-chest-storage-one"].subgroup = "dytech-storage"
	data.raw.item["logistic-chest-storage-one"].order = "9"
	data.raw.item["logistic-chest-requester-1"].subgroup = "dytech-request"
	data.raw.item["logistic-chest-requester-1"].order = "2"
	data.raw.item["logistic-chest-requester-2"].subgroup = "dytech-request"
	data.raw.item["logistic-chest-requester-2"].order = "3"
end
if data.raw.item["logistic-chest-requester-medium"] then

	data.raw.item["logistic-chest-passive-provider-medium"].subgroup = "dytech-passive"
	data.raw.item["logistic-chest-passive-provider-medium"].order = "4"
	data.raw.item["logistic-chest-passive-provider-big"].subgroup = "dytech-passive"
	data.raw.item["logistic-chest-passive-provider-big"].order = "5"
	data.raw.item["logistic-chest-active-provider-medium"].subgroup = "dytech-active"
	data.raw.item["logistic-chest-active-provider-medium"].order = "4"
	data.raw.item["logistic-chest-active-provider-big"].subgroup = "dytech-active"
	data.raw.item["logistic-chest-active-provider-big"].order = "5"
	data.raw.item["logistic-chest-storage-medium"].subgroup = "dytech-storage"
	data.raw.item["logistic-chest-storage-medium"].order = "4"
	data.raw.item["logistic-chest-storage-big"].subgroup = "dytech-storage"
	data.raw.item["logistic-chest-storage-big"].order = "5"
	data.raw.item["logistic-chest-requester-medium"].subgroup = "dytech-request"
	data.raw.item["logistic-chest-requester-medium"].order = "4"
	data.raw.item["logistic-chest-requester-big"].subgroup = "dytech-request"
	data.raw.item["logistic-chest-requester-big"].order = "5"
end

--------------------------[[ Ores ]] ------------------

data.raw.item["iron-ore"].subgroup = "metallurgy-ores-clean"
data.raw.item["iron-ore"].order = "1"
data.raw.item["copper-ore"].subgroup = "metallurgy-ores-clean"
data.raw.item["copper-ore"].order = "2"
data.raw.item["iron-plate"].subgroup = "metallurgy-plates"
data.raw.item["iron-plate"].order = "1"
data.raw.item["copper-plate"].subgroup = "metallurgy-plates"
data.raw.item["copper-plate"].order = "2"
data.raw.item["steel-plate"].subgroup = "metallurgy-plates"
data.raw.item["steel-plate"].order = "3"

if data.raw.item["metallurgy-active"] then
	data.raw.item["dirty-iron-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-iron-ore"].order = "1"
	data.raw.item["dirty-copper-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-copper-ore"].order = "2"
	data.raw.item["dirty-tin-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-tin-ore"].order = "3"
	data.raw.item["dirty-bauxite-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-bauxite-ore"].order = "4"
	data.raw.item["dirty-zinc-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-zinc-ore"].order = "5"
	data.raw.item["dirty-lead-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-lead-ore"].order = "6"
	data.raw.item["dirty-silver-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-silver-ore"].order = "7"
	data.raw.item["dirty-gold-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-gold-ore"].order = "8"
	data.raw.item["dirty-rutile-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-rutile-ore"].order = "9"
	data.raw.item["dirty-tungsten-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-tungsten-ore"].order = "91"
	data.raw.item["dirty-cobalt-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-cobalt-ore"].order = "92"
	data.raw.item["dirty-chromite-ore"].subgroup = "metallurgy-ores"
	data.raw.item["dirty-chromite-ore"].order = "93"
	data.raw.item["tin-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["tin-ore"].order = "3"
	data.raw.item["bauxite-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["bauxite-ore"].order = "4"
	data.raw.item["zinc-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["zinc-ore"].order = "5"
	data.raw.item["lead-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["lead-ore"].order = "6"
	data.raw.item["silver-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["silver-ore"].order = "7"
	data.raw.item["gold-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["gold-ore"].order = "8"
	data.raw.item["rutile-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["rutile-ore"].order = "9"
	data.raw.item["tungsten-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["tungsten-ore"].order = "91"
	data.raw.item["cobalt-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["cobalt-ore"].order = "92"
	data.raw.item["chromite-ore"].subgroup = "metallurgy-ores-clean"
	data.raw.item["chromite-ore"].order = "93"
	data.raw.item["steel-plate-01"].subgroup = "metallurgy-plates"
	data.raw.item["steel-plate-01"].order = "5"
	data.raw.item["tin-plate"].subgroup = "metallurgy-plates"
	data.raw.item["tin-plate"].order = "5"
	data.raw.item["aluminium-plate"].subgroup = "metallurgy-plates"
	data.raw.item["aluminium-plate"].order = "6"
	data.raw.item["zinc-plate"].subgroup = "metallurgy-plates"
	data.raw.item["zinc-plate"].order = "7"
	data.raw.item["lead-plate"].subgroup = "metallurgy-plates"
	data.raw.item["lead-plate"].order = "8"
	data.raw.item["silver-plate"].subgroup = "metallurgy-plates"
	data.raw.item["silver-plate"].order = "9"
	data.raw.item["gold-plate"].subgroup = "metallurgy-plates"
	data.raw.item["gold-plate"].order = "91"
	data.raw.item["titanium-plate"].subgroup = "metallurgy-plates"
	data.raw.item["titanium-plate"].order = "92"
	data.raw.item["tungsten-plate"].subgroup = "metallurgy-plates"
	data.raw.item["tungsten-plate"].order = "93"
	data.raw.item["cobalt-plate"].subgroup = "metallurgy-plates"
	data.raw.item["cobalt-plate"].order = "94"
end

--------------------------[[ Power ]] ------------------

data.raw.item["offshore-pump"].subgroup = "dytech-energy-offshore"
data.raw.item["offshore-pump"].order = "1"
data.raw.item["steam-engine"].subgroup = "dytech-energy-steam-primary"
data.raw.item["steam-engine"].order = "1"
data.raw.item["boiler"].subgroup = "dytech-energy-boiler"
data.raw.item["boiler"].order = "1"
data.raw.item["small-electric-pole"].subgroup = "dytech-energy-poles"
data.raw.item["small-electric-pole"].order = "1"
data.raw.item["medium-electric-pole"].subgroup = "dytech-energy-poles"
data.raw.item["medium-electric-pole"].order = "2"
data.raw.item["big-electric-pole"].subgroup = "dytech-energy-poles"
data.raw.item["big-electric-pole"].order = "3"
data.raw.item["substation"].subgroup = "dytech-energy-poles"
data.raw.item["substation"].order = "4"
data.raw.item["small-lamp"].subgroup = "dytech-energy-lamp"
data.raw.item["small-lamp"].order = "1"

if data.raw.item["small-lamp-1"] then
	data.raw.item["small-lamp-1"].subgroup = "dytech-energy-lamp"
	data.raw.item["small-lamp-1"].order = "2"
	data.raw.item["small-lamp-2"].subgroup = "dytech-energy-lamp"
	data.raw.item["small-lamp-2"].order = "3"
end
if data.raw.item["offshore-pump-mk2"] then
	data.raw.item["offshore-pump-mk2"].subgroup = "dytech-energy-offshore"
	data.raw.item["offshore-pump-mk2"].order = "2"
	data.raw.item["offshore-pump-mk3"].subgroup = "dytech-energy-offshore"
	data.raw.item["offshore-pump-mk3"].order = "3"
	data.raw.item["offshore-pump-mk4"].subgroup = "dytech-energy-offshore"
	data.raw.item["offshore-pump-mk4"].order = "4"
	data.raw.item["offshore-pump-mk5"].subgroup = "dytech-energy-offshore"
	data.raw.item["offshore-pump-mk5"].order = "5"
end
if data.raw.item["boiler-mk2"] then
	data.raw.item["boiler-mk2"].subgroup = "dytech-energy-boiler"
	data.raw.item["boiler-mk2"].order = "2"
	data.raw.item["boiler-mk3"].subgroup = "dytech-energy-boiler"
	data.raw.item["boiler-mk3"].order = "3"
	data.raw.item["boiler-mk4"].subgroup = "dytech-energy-boiler"
	data.raw.item["boiler-mk4"].order = "4"
	data.raw.item["boiler-mk5"].subgroup = "dytech-energy-boiler"
	data.raw.item["boiler-mk5"].order = "5"
end
if data.raw.item["high-boiler-mk1"] then
	data.raw.item["high-boiler-mk1"].subgroup = "dytech-energy-boiler-high"
	data.raw.item["high-boiler-mk1"].order = "1"
	data.raw.item["high-boiler-mk2"].subgroup = "dytech-energy-boiler-high"
	data.raw.item["high-boiler-mk2"].order = "2"
	data.raw.item["high-boiler-mk3"].subgroup = "dytech-energy-boiler-high"
	data.raw.item["high-boiler-mk3"].order = "3"
	data.raw.item["high-boiler-mk4"].subgroup = "dytech-energy-boiler-high"
	data.raw.item["high-boiler-mk4"].order = "4"
	data.raw.item["high-boiler-mk5"].subgroup = "dytech-energy-boiler-high"
	data.raw.item["high-boiler-mk5"].order = "5"
end
if data.raw.item["steam-engine-mk2"] then
	data.raw.item["steam-engine-mk2"].subgroup = "dytech-energy-steam-primary"
	data.raw.item["steam-engine-mk2"].order = "2"
	data.raw.item["steam-engine-mk3"].subgroup = "dytech-energy-steam-primary"
	data.raw.item["steam-engine-mk3"].order = "3"
	data.raw.item["steam-engine-mk4"].subgroup = "dytech-energy-steam-primary"
	data.raw.item["steam-engine-mk4"].order = "4"
	data.raw.item["steam-engine-mk5"].subgroup = "dytech-energy-steam-primary"
	data.raw.item["steam-engine-mk5"].order = "5"
end
if data.raw.item["high-steam-engine"] then
	data.raw.item["high-steam-engine"].subgroup = "dytech-energy-steam-secondary"
	data.raw.item["high-steam-engine"].order = "1"
	data.raw.item["high-steam-engine-mk2"].subgroup = "dytech-energy-steam-secondary"
	data.raw.item["high-steam-engine-mk2"].order = "2"
	data.raw.item["high-steam-engine-mk3"].subgroup = "dytech-energy-steam-secondary"
	data.raw.item["high-steam-engine-mk3"].order = "3"
	data.raw.item["high-steam-engine-mk4"].subgroup = "dytech-energy-steam-secondary"
	data.raw.item["high-steam-engine-mk4"].order = "4"
	data.raw.item["high-steam-engine-mk5"].subgroup = "dytech-energy-steam-secondary"
	data.raw.item["high-steam-engine-mk5"].order = "5"
end
if data.raw.item["large-solar-panel"] then
	data.raw.recipe["large-solar-panel-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["large-solar-panel-2"].order = "1"
	data.raw.recipe["large-solar-panel-mk2-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["large-solar-panel-mk2-2"].order = "3"
	data.raw.recipe["large-solar-panel-mk3-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["large-solar-panel-mk3-2"].order = "5"
	data.raw.recipe["large-solar-panel-mk4-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["large-solar-panel-mk4-2"].order = "7"
	data.raw.recipe["large-solar-panel-mk5-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["large-solar-panel-mk5-2"].order = "9"
	

end
if data.raw.item["small-solar-panel"] then
	data.raw.recipe["small-solar-panel-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["small-solar-panel-2"].order = "2"
	data.raw.recipe["small-solar-panel-mk2-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["small-solar-panel-mk2-2"].order = "4"
	data.raw.recipe["small-solar-panel-mk3-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["small-solar-panel-mk3-2"].order = "6"
	data.raw.recipe["small-solar-panel-mk4-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["small-solar-panel-mk4-2"].order = "8"
	data.raw.recipe["small-solar-panel-mk5-2"].subgroup = "dytech-energy-solar-normal-2"
	data.raw.recipe["small-solar-panel-mk5-2"].order = "91"
end

--------------------------[[ Trains ]] ------------------

data.raw["rail-planner"]["rail"].subgroup = "dytech-rail"
data.raw["rail-planner"]["rail"].order = "1"
data.raw.item["rail-signal"].subgroup = "dytech-signal"
data.raw.item["rail-signal"].order = "1"
data.raw.item["rail-chain-signal"].subgroup = "dytech-signal"
data.raw.item["rail-chain-signal"].order = "2"
data.raw.item["train-stop"].subgroup = "dytech-station"
data.raw.item["train-stop"].order = "1"
data.raw["item-with-entity-data"]["diesel-locomotive"].subgroup = "dytech-train"
data.raw["item-with-entity-data"]["diesel-locomotive"].order = "1"
data.raw["item-with-entity-data"]["cargo-wagon"].subgroup = "dytech-wagon"
data.raw["item-with-entity-data"]["cargo-wagon"].order = "1"

if data.raw.item["diesel-locomotive-armor"] then
	data.raw.item["diesel-locomotive-armor"].subgroup = "dytech-train"
	data.raw.item["diesel-locomotive-armor"].order = "2"
	data.raw.item["cargo-wagon-armor"].subgroup = "dytech-wagon"
	data.raw.item["cargo-wagon-armor"].order = "2"
end
if data.raw.item["diesel-locomotive-fast"] then
	data.raw.item["diesel-locomotive-fast"].subgroup = "dytech-train"
	data.raw.item["diesel-locomotive-fast"].order = "3"
	data.raw.item["cargo-wagon-fast"].subgroup = "dytech-wagon"
	data.raw.item["cargo-wagon-fast"].order = "3"
end

--------------------------[[ Defense ]] ------------------

data.raw.item["stone-wall"].subgroup = "dytech-wall"
data.raw.item["stone-wall"].order = "1"
data.raw.item["gate"].subgroup = "dytech-gate"
data.raw.item["gate"].order = "1"
data.raw.item["gun-turret"].subgroup = "dytech-turret"
data.raw.item["gun-turret"].order = "1"
data.raw.item["flamethrower-turret"].subgroup = "dytech-turret"
data.raw.item["flamethrower-turret"].order = "2"
data.raw.item["land-mine"].subgroup = "dytech-turret"
data.raw.item["land-mine"].order = "3"
data.raw.item["laser-turret"].subgroup = "dytech-turret-laser"
data.raw.item["laser-turret"].order = "1"
data.raw.item["radar"].subgroup = "dytech-radar"
data.raw.item["radar"].order = "1"

if data.raw.item["sand-wall"] then
	data.raw.item["sand-wall"].subgroup = "dytech-wall"
	data.raw.item["sand-wall"].order = "2"
end
if data.raw.item["brick-wall"] then
	data.raw.item["brick-wall"].subgroup = "dytech-wall"
	data.raw.item["brick-wall"].order = "3"
end
if data.raw.item["chitin-wall"] then
	data.raw.item["chitin-wall"].subgroup = "dytech-wall"
	data.raw.item["chitin-wall"].order = "4"
end
if data.raw.item["tungsten-wall"] then
	data.raw.item["tungsten-wall"].subgroup = "dytech-wall"
	data.raw.item["tungsten-wall"].order = "5"
end
if data.raw.item["sand-wall-gate"] then
	data.raw.item["sand-wall-gate"].subgroup = "dytech-gate"
	data.raw.item["sand-wall-gate"].order = "2"
end
if data.raw.item["brick-wall-gate"] then
	data.raw.item["brick-wall-gate"].subgroup = "dytech-gate"
	data.raw.item["brick-wall-gate"].order = "3"
end
if data.raw.item["chitin-wall-gate"] then
	data.raw.item["chitin-wall-gate"].subgroup = "dytech-gate"
	data.raw.item["chitin-wall-gate"].order = "4"
end
if data.raw.item["tungsten-wall-gate"] then
	data.raw.item["tungsten-wall-gate"].subgroup = "dytech-gate"
	data.raw.item["tungsten-wall-gate"].order = "5"
end
if data.raw.item["radar-mk2"] then
	data.raw.item["radar-mk2"].subgroup = "dytech-radar"
	data.raw.item["radar-mk2"].order = "2"
	data.raw.item["radar-mk3"].subgroup = "dytech-radar"
	data.raw.item["radar-mk3"].order = "3"
	data.raw.item["radar-mk4"].subgroup = "dytech-radar"
	data.raw.item["radar-mk4"].order = "4"
	data.raw.item["radar-mk5"].subgroup = "dytech-radar"
	data.raw.item["radar-mk5"].order = "5"
end
if data.raw.item["sniper-turret"] then
	data.raw.item["sniper-turret"].subgroup = "dytech-turret"
	data.raw.item["sniper-turret"].order = "3"
end
if data.raw.item["gun-turret-1"] then
	data.raw.item["gun-turret-1"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-1"].order = "4"
	data.raw.item["gun-turret-2"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-2"].order = "5"
	data.raw.item["gun-turret-3"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-3"].order = "6"
	data.raw.item["gun-turret-4"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-4"].order = "7"
	data.raw.item["gun-turret-5"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-5"].order = "8"
	data.raw.item["gun-turret-6"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-6"].order = "9"
	data.raw.item["gun-turret-7"].subgroup = "dytech-turret-2"
	data.raw.item["gun-turret-7"].order = "91"
end
if data.raw.item["gun-turret-1-armored"] then
	data.raw.item["gun-turret-1-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-1-armored"].order = "4"
	data.raw.item["gun-turret-2-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-2-armored"].order = "5"
	data.raw.item["gun-turret-3-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-3-armored"].order = "6"
	data.raw.item["gun-turret-4-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-4-armored"].order = "7"
	data.raw.item["gun-turret-5-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-5-armored"].order = "8"
	data.raw.item["gun-turret-6-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-6-armored"].order = "9"
	data.raw.item["gun-turret-7-armored"].subgroup = "dytech-turret-armor"
	data.raw.item["gun-turret-7-armored"].order = "91"
end
if data.raw.item["laser-turret-2"] then
	data.raw.item["laser-turret-2"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-2"].order = "2"
	data.raw.item["laser-turret-3"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-3"].order = "3"
	data.raw.item["laser-turret-4"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-4"].order = "4"
	data.raw.item["laser-turret-5"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-5"].order = "5"
	data.raw.item["laser-turret-6"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-6"].order = "6"
	data.raw.item["laser-turret-7"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-7"].order = "7"
	data.raw.item["laser-turret-8"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-8"].order = "8"
	data.raw.item["laser-turret-9"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-9"].order = "9"
	data.raw.item["laser-turret-sniper-1"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-sniper-1"].order = "91"
	data.raw.item["laser-turret-sniper-2"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-sniper-2"].order = "92"
	data.raw.item["laser-turret-sniper-3"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-sniper-3"].order = "93"
	data.raw.item["laser-turret-diamond-1"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-diamond-1"].order = "94"
	data.raw.item["laser-turret-diamond-2"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-diamond-2"].order = "95"
	data.raw.item["laser-turret-diamond-3"].subgroup = "dytech-turret-laser"
	data.raw.item["laser-turret-diamond-3"].order = "96"

end

--------------------------[[ Armor ]] ------------------

data.raw.armor["light-armor"].subgroup = "dytech-armor"
data.raw.armor["light-armor"].order = "1"
data.raw.armor["heavy-armor"].subgroup = "dytech-armor"
data.raw.armor["heavy-armor"].order = "2"
data.raw.armor["modular-armor"].subgroup = "dytech-armor"
data.raw.armor["modular-armor"].order = "3"
data.raw.armor["power-armor"].subgroup = "dytech-armor"
data.raw.armor["power-armor"].order = "4"
data.raw.armor["power-armor-mk2"].subgroup = "dytech-armor"
data.raw.armor["power-armor-mk2"].order = "5"
data.raw.item["solar-panel-equipment"].subgroup = "dytech-solar-equipment"
data.raw.item["solar-panel-equipment"].order = "1"
data.raw.item["fusion-reactor-equipment"].subgroup = "dytech-fusion-equipment"
data.raw.item["fusion-reactor-equipment"].order = "1"
data.raw.item["energy-shield-equipment"].subgroup = "dytech-shield-equipment"
data.raw.item["energy-shield-equipment"].order = "1"
data.raw.item["energy-shield-mk2-equipment"].subgroup = "dytech-shield-equipment"
data.raw.item["energy-shield-mk2-equipment"].order = "2"
data.raw.item["battery-equipment"].subgroup = "dytech-battery-equipment"
data.raw.item["battery-equipment"].order = "1"
data.raw.item["battery-mk2-equipment"].subgroup = "dytech-battery-equipment"
data.raw.item["battery-mk2-equipment"].order = "2"
data.raw.item["personal-laser-defense-equipment"].subgroup = "dytech-laser-equipment"
data.raw.item["personal-laser-defense-equipment"].order = "1"
data.raw.item["exoskeleton-equipment"].subgroup = "dytech-exo-equipment"
data.raw.item["exoskeleton-equipment"].order = "1"
data.raw.item["discharge-defense-equipment"].subgroup = "dytech-misc-equipment"
data.raw.item["discharge-defense-equipment"].order = "1"
data.raw.capsule["discharge-defense-remote"].subgroup = "dytech-misc-equipment"
data.raw.capsule["discharge-defense-remote"].order = "11"
data.raw.item["night-vision-equipment"].subgroup = "dytech-misc-equipment"
data.raw.item["night-vision-equipment"].order = "2"
data.raw.item["personal-roboport-equipment"].subgroup = "dytech-misc-equipment"
data.raw.item["personal-roboport-equipment"].order = "3"


if data.raw.item["personal-roboport-equipment-1"] then
	data.raw.item["personal-roboport-equipment-1"].subgroup = "dytech-misc-equipment"
	data.raw.item["personal-roboport-equipment-1"].order = "4"
	data.raw.item["personal-roboport-equipment-2"].subgroup = "dytech-misc-equipment"
	data.raw.item["personal-roboport-equipment-2"].order = "5"
end
if data.raw.item["exoskeleton-mk2-equipment"] then
	data.raw.item["exoskeleton-mk2-equipment"].subgroup = "dytech-exo-equipment"
	data.raw.item["exoskeleton-mk2-equipment"].order = "2"
	data.raw.item["exoskeleton-mk3-equipment"].subgroup = "dytech-exo-equipment"
	data.raw.item["exoskeleton-mk3-equipment"].order = "2"
	data.raw.item["exoskeleton-mk4-equipment"].subgroup = "dytech-exo-equipment"
	data.raw.item["exoskeleton-mk4-equipment"].order = "2"
	data.raw.item["exoskeleton-mk5-equipment"].subgroup = "dytech-exo-equipment"
	data.raw.item["exoskeleton-mk5-equipment"].order = "2"
	data.raw.item["exoskeleton-mk6-equipment"].subgroup = "dytech-exo-equipment"
	data.raw.item["exoskeleton-mk6-equipment"].order = "2"
	data.raw.item["exoskeleton-mk7-equipment"].subgroup = "dytech-exo-equipment"
	data.raw.item["exoskeleton-mk7-equipment"].order = "2"
end
if data.raw.item["laser-defense-equipment-2"] then
	data.raw.item["laser-defense-equipment-2"].subgroup = "dytech-laser-equipment"
	data.raw.item["laser-defense-equipment-2"].order = "2"
	data.raw.item["laser-defense-equipment-3"].subgroup = "dytech-laser-equipment"
	data.raw.item["laser-defense-equipment-3"].order = "3"
	data.raw.item["laser-defense-mk4-equipment"].subgroup = "dytech-laser-equipment"
	data.raw.item["laser-defense-mk4-equipment"].order = "4"
	data.raw.item["laser-defense-mk5-equipment"].subgroup = "dytech-laser-equipment"
	data.raw.item["laser-defense-mk5-equipment"].order = "5"
	data.raw.item["laser-defense-mk6-equipment"].subgroup = "dytech-laser-equipment"
	data.raw.item["laser-defense-mk6-equipment"].order = "6"
	data.raw.item["laser-defense-mk7-equipment"].subgroup = "dytech-laser-equipment"
	data.raw.item["laser-defense-mk7-equipment"].order = "7"
end
if data.raw.item["battery-mk3-equipment"] then
	data.raw.item["battery-mk3-equipment"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk3-equipment"].order = "3"
	data.raw.item["battery-mk4-equipment"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk4-equipment"].order = "4"
	data.raw.item["battery-mk5-equipment"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk5-equipment"].order = "5"
	data.raw.item["battery-mk6-equipment"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk6-equipment"].order = "6"
	data.raw.item["battery-mk7-equipment"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk7-equipment"].order = "7"
	data.raw.item["battery-mk3-equipment-horizontal"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk3-equipment-horizontal"].order = "31"
	data.raw.item["battery-mk4-equipment-horizontal"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk4-equipment-horizontal"].order = "41"
	data.raw.item["battery-mk5-equipment-horizontal"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk5-equipment-horizontal"].order = "51"
	data.raw.item["battery-mk6-equipment-horizontal"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk6-equipment-horizontal"].order = "61"
	data.raw.item["battery-mk7-equipment-horizontal"].subgroup = "dytech-battery-equipment"
	data.raw.item["battery-mk7-equipment-horizontal"].order = "71"
	
end
if data.raw.item["energy-shield-mk3-equipment"] then
	data.raw.item["energy-shield-mk3-equipment"].subgroup = "dytech-shield-equipment"
	data.raw.item["energy-shield-mk3-equipment"].order = "3"
	data.raw.item["energy-shield-mk4-equipment"].subgroup = "dytech-shield-equipment"
	data.raw.item["energy-shield-mk4-equipment"].order = "4"
	data.raw.item["energy-shield-mk5-equipment"].subgroup = "dytech-shield-equipment"
	data.raw.item["energy-shield-mk5-equipment"].order = "5"
	data.raw.item["energy-shield-mk6-equipment"].subgroup = "dytech-shield-equipment"
	data.raw.item["energy-shield-mk6-equipment"].order = "6"
	data.raw.item["energy-shield-mk7-equipment"].subgroup = "dytech-shield-equipment"
	data.raw.item["energy-shield-mk7-equipment"].order = "7"
end
if data.raw.item["fusion-reactor-mk2-equipment"] then
	data.raw.item["fusion-reactor-mk2-equipment"].subgroup = "dytech-fusion-equipment"
	data.raw.item["fusion-reactor-mk2-equipment"].order = "2"
	data.raw.item["fusion-reactor-mk3-equipment"].subgroup = "dytech-fusion-equipment"
	data.raw.item["fusion-reactor-mk3-equipment"].order = "3"
	data.raw.item["fusion-reactor-mk4-equipment"].subgroup = "dytech-fusion-equipment"
	data.raw.item["fusion-reactor-mk4-equipment"].order = "4"
	data.raw.item["fusion-reactor-mk5-equipment"].subgroup = "dytech-fusion-equipment"
	data.raw.item["fusion-reactor-mk5-equipment"].order = "5"
	data.raw.item["fusion-reactor-mk6-equipment"].subgroup = "dytech-fusion-equipment"
	data.raw.item["fusion-reactor-mk6-equipment"].order = "6"
	data.raw.item["fusion-reactor-mk7-equipment"].subgroup = "dytech-fusion-equipment"
	data.raw.item["fusion-reactor-mk7-equipment"].order = "7"
end
if data.raw.item["solar-panel-equipment-2"] then
	data.raw.item["solar-panel-equipment-2"].subgroup = "dytech-solar-equipment"
	data.raw.item["solar-panel-equipment-2"].order = "2"
	data.raw.item["solar-panel-equipment-3"].subgroup = "dytech-solar-equipment"
	data.raw.item["solar-panel-equipment-3"].order = "3"
	data.raw.item["solar-panel-equipment-4"].subgroup = "dytech-solar-equipment"
	data.raw.item["solar-panel-equipment-4"].order = "4"
	data.raw.item["solar-panel-equipment-5"].subgroup = "dytech-solar-equipment"
	data.raw.item["solar-panel-equipment-5"].order = "5"
end
if data.raw.armor["power-armor-mk3"] then
	data.raw.armor["power-armor-mk3"].subgroup = "dytech-armor"
	data.raw.armor["power-armor-mk3"].order = "6"
	data.raw.armor["power-armor-mk4"].subgroup = "dytech-armor"
	data.raw.armor["power-armor-mk4"].order = "7"
	data.raw.armor["power-armor-mk5"].subgroup = "dytech-armor"
	data.raw.armor["power-armor-mk5"].order = "8"
	data.raw.armor["power-armor-mk6"].subgroup = "dytech-armor"
	data.raw.armor["power-armor-mk6"].order = "9"
	data.raw.armor["power-armor-mk7"].subgroup = "dytech-armor"
	data.raw.armor["power-armor-mk7"].order = "91"
end

--------------------------[[ Fluids ]] ------------------

data.raw.recipe["dirty-water-sand"].subgroup = "dytech-fluid-cleaning"
data.raw.recipe["dirty-water-sand"].order = "1"
data.raw.recipe["dirty-water-stone"].subgroup = "dytech-fluid-cleaning"
data.raw.recipe["dirty-water-stone"].order = "2"
data.raw.recipe["dirty-water-stone-sand-random"].subgroup = "dytech-fluid-cleaning"
data.raw.recipe["dirty-water-stone-sand-random"].order = "3"
data.raw.recipe["dirty-water-to-water"].subgroup = "dytech-fluid-cleaning"
data.raw.recipe["dirty-water-to-water"].order = "4"
data.raw.recipe["dirty-water-to-water-2"].subgroup = "dytech-fluid-cleaning"
data.raw.recipe["dirty-water-to-water-2"].order = "5"
if data.raw.item["metallurgy-active"] then
	data.raw.recipe["sand-purify"].subgroup = "dytech-fluid-cleaning"
	data.raw.recipe["sand-purify"].order = "6"
	data.raw.recipe["sludge-processing"].subgroup = "dytech-fluid-cleaning"
	data.raw.recipe["sludge-processing"].order = "7"
	data.raw.recipe["coal-splitting"].subgroup = "dytech-fluid-cleaning"
	data.raw.recipe["coal-splitting"].order = "7"
	data.raw.item["solder"].subgroup = "liquid-crafting-circuit"
	data.raw.item["solder"].order = "99"
end

data.raw.item["sulfur"].subgroup = "dytech-fluid-processing"
data.raw.item["sulfur"].order = "1"
data.raw.recipe["sulfuric-acid"].subgroup = "dytech-fluid-processing"
data.raw.recipe["sulfuric-acid"].order = "2"
data.raw.recipe["lubricant"].subgroup = "dytech-fluid-processing"
data.raw.recipe["lubricant"].order = "3"
data.raw.item["plastic-bar"].subgroup = "dytech-fluid-processing"
data.raw.item["plastic-bar"].order = "4"
data.raw.recipe["solid-fuel-from-heavy-oil"].subgroup = "dytech-fluid-processing"
data.raw.recipe["solid-fuel-from-heavy-oil"].order = "5"
data.raw.recipe["solid-fuel-from-light-oil"].subgroup = "dytech-fluid-processing"
data.raw.recipe["solid-fuel-from-light-oil"].order = "6"
data.raw.recipe["solid-fuel-from-petroleum-gas"].subgroup = "dytech-fluid-processing"
data.raw.recipe["solid-fuel-from-petroleum-gas"].order = "7"
data.raw.recipe["rocket-fuel"].subgroup = "dytech-fluid-processing"
data.raw.recipe["rocket-fuel"].order = "8"

data.raw.recipe["basic-oil-processing"].subgroup = "dytech-fluid-oil-processing"
data.raw.recipe["basic-oil-processing"].order = "1"
data.raw.recipe["advanced-oil-processing"].subgroup = "dytech-fluid-oil-processing"
data.raw.recipe["advanced-oil-processing"].order = "2"
data.raw.recipe["heavy-oil-cracking"].subgroup = "dytech-fluid-oil-processing"
data.raw.recipe["heavy-oil-cracking"].order = "3"
data.raw.recipe["light-oil-cracking"].subgroup = "dytech-fluid-oil-processing"
data.raw.recipe["light-oil-cracking"].order = "4"
data.raw.recipe["fill-crude-oil-barrel"].subgroup = "dytech-fluid-oil-processing"
data.raw.recipe["fill-crude-oil-barrel"].order = "5"
data.raw.recipe["empty-crude-oil-barrel"].subgroup = "dytech-fluid-oil-processing"
data.raw.recipe["empty-crude-oil-barrel"].order = "6"


--------------------------[[ Combat ]] ------------------

data.raw.gun["pistol"].subgroup = "dytech-combat-guns"
data.raw.gun["pistol"].order = "1"
data.raw.gun["submachine-gun"].subgroup = "dytech-combat-guns"
data.raw.gun["submachine-gun"].order = "2"
data.raw.gun["shotgun"].subgroup = "dytech-combat-guns-2"
data.raw.gun["shotgun"].order = "1"
data.raw.gun["combat-shotgun"].subgroup = "dytech-combat-guns-2"
data.raw.gun["combat-shotgun"].order = "2"
data.raw.gun["flame-thrower"].subgroup = "dytech-combat-guns-3"
data.raw.gun["flame-thrower"].order = "1"
data.raw.gun["rocket-launcher"].subgroup = "dytech-combat-guns-3"
data.raw.gun["rocket-launcher"].order = "2"
data.raw.capsule["grenade"].subgroup = "dytech-combat-grenade"
data.raw.capsule["grenade"].order = "1"
data.raw.capsule["cluster-grenade"].subgroup = "dytech-combat-grenade"
data.raw.capsule["cluster-grenade"].order = "2"
data.raw.ammo["firearm-magazine"].subgroup = "dytech-combat-ammo"
data.raw.ammo["firearm-magazine"].order = "1"
data.raw.ammo["piercing-rounds-magazine"].subgroup = "dytech-combat-ammo"
data.raw.ammo["piercing-rounds-magazine"].order = "2"
data.raw.ammo["flame-thrower-ammo"].subgroup = "dytech-combat-ammo-misc"
data.raw.ammo["flame-thrower-ammo"].order = "1"
data.raw.ammo["rocket"].subgroup = "dytech-combat-ammo-misc"
data.raw.ammo["rocket"].order = "2"
data.raw.ammo["explosive-rocket"].subgroup = "dytech-combat-ammo-misc"
data.raw.ammo["explosive-rocket"].order = "3"
data.raw.ammo["cannon-shell"].subgroup = "dytech-combat-ammo-misc"
data.raw.ammo["cannon-shell"].order = "4"
data.raw.ammo["explosive-cannon-shell"].subgroup = "dytech-combat-ammo-misc"
data.raw.ammo["explosive-cannon-shell"].order = "5"
data.raw.ammo["railgun-dart"].subgroup = "dytech-combat-ammo-misc"
data.raw.ammo["railgun-dart"].order = "7"
data.raw.ammo["shotgun-shell"].subgroup = "dytech-combat-ammo-shotgun"
data.raw.ammo["shotgun-shell"].order = "1"
data.raw.ammo["piercing-shotgun-shell"].subgroup = "dytech-combat-ammo-shotgun"
data.raw.ammo["piercing-shotgun-shell"].order = "2"
data.raw.capsule["defender-capsule"].subgroup = "dytech-combat-robot-capsules"
data.raw.capsule["defender-capsule"].order = "1"
data.raw.capsule["distractor-capsule"].subgroup = "dytech-combat-robot-capsules"
data.raw.capsule["distractor-capsule"].order = "2"
data.raw.capsule["destroyer-capsule"].subgroup = "dytech-combat-robot-capsules"
data.raw.capsule["destroyer-capsule"].order = "3"
data.raw.capsule["poison-capsule"].subgroup = "dytech-combat-capsules"
data.raw.capsule["poison-capsule"].order = "1"
data.raw.capsule["slowdown-capsule"].subgroup = "dytech-combat-capsules"
data.raw.capsule["slowdown-capsule"].order = "2"
data.raw["item-with-entity-data"]["tank"].subgroup = "dytech-combat-transport"
data.raw["item-with-entity-data"]["tank"].order = "3"
data.raw["item-with-entity-data"]["car"].subgroup = "dytech-combat-transport"
data.raw["item-with-entity-data"]["car"].order = "1"
if data.raw.item["machines-active"] then
	data.raw["item-with-entity-data"]["car2"].subgroup = "dytech-combat-transport"
	data.raw["item-with-entity-data"]["car2"].order = "2"
end
if data.raw.item["tank-dytech-1"] then
	data.raw.item["tank-dytech-1"].subgroup = "dytech-combat-transport"
	data.raw.item["tank-dytech-1"].order = "4"
	data.raw.item["tank-dytech-2"].subgroup = "dytech-combat-transport"
	data.raw.item["tank-dytech-2"].order = "4"
end

if data.raw.capsule["poison-capsule-1"] then
	data.raw.capsule["poison-capsule-1"].subgroup = "dytech-combat-capsules-2"
	data.raw.capsule["poison-capsule-1"].order = "1"
	data.raw.capsule["poison-capsule-2"].subgroup = "dytech-combat-capsules-3"
	data.raw.capsule["poison-capsule-2"].order = "1"
end
if data.raw.capsule["slowdown-capsule-1"] then
	data.raw.capsule["slowdown-capsule-1"].subgroup = "dytech-combat-capsules-2"
	data.raw.capsule["slowdown-capsule-1"].order = "2"
	data.raw.capsule["slowdown-capsule-2"].subgroup = "dytech-combat-capsules-3"
	data.raw.capsule["slowdown-capsule-2"].order = "2"
end
if data.raw.capsule["acid-capsule-1"] then
	data.raw.capsule["acid-capsule-1"].subgroup = "dytech-combat-capsules"
	data.raw.capsule["acid-capsule-1"].order = "3"
	data.raw.capsule["acid-capsule-2"].subgroup = "dytech-combat-capsules-2"
	data.raw.capsule["acid-capsule-2"].order = "3"
	data.raw.capsule["acid-capsule-3"].subgroup = "dytech-combat-capsules-3"
	data.raw.capsule["acid-capsule-3"].order = "3"
end
if data.raw.capsule["firestorm-capsule-1"] then
	data.raw.capsule["firestorm-capsule-1"].subgroup = "dytech-combat-capsules"
	data.raw.capsule["firestorm-capsule-1"].order = "4"
	data.raw.capsule["firestorm-capsule-2"].subgroup = "dytech-combat-capsules-2"
	data.raw.capsule["firestorm-capsule-2"].order = "4"
	data.raw.capsule["firestorm-capsule-3"].subgroup = "dytech-combat-capsules-3"
	data.raw.capsule["firestorm-capsule-3"].order = "4"
end
if data.raw.capsule["napalm-capsule-1"] then
	data.raw.capsule["napalm-capsule-1"].subgroup = "dytech-combat-capsules"
	data.raw.capsule["napalm-capsule-1"].order = "5"
	data.raw.capsule["napalm-capsule-2"].subgroup = "dytech-combat-capsules-2"
	data.raw.capsule["napalm-capsule-2"].order = "5"
	data.raw.capsule["napalm-capsule-3"].subgroup = "dytech-combat-capsules-3"
	data.raw.capsule["napalm-capsule-3"].order = "5"
end
if data.raw.capsule["radiation-capsule-1"] then
	data.raw.capsule["radiation-capsule-1"].subgroup = "dytech-combat-capsules"
	data.raw.capsule["radiation-capsule-1"].order = "7"
	data.raw.capsule["radiation-capsule-2"].subgroup = "dytech-combat-capsules-2"
	data.raw.capsule["radiation-capsule-2"].order = "7"
	data.raw.capsule["radiation-capsule-3"].subgroup = "dytech-combat-capsules-3"
	data.raw.capsule["radiation-capsule-3"].order = "7"
end
if data.raw.ammo["acid-capsule-ammo-1"] then
	data.raw.ammo["acid-capsule-ammo-1"].subgroup = "dytech-combat-ammo-capsules"
	data.raw.ammo["acid-capsule-ammo-1"].order = "3"
	data.raw.ammo["acid-capsule-ammo-2"].subgroup = "dytech-combat-ammo-capsules-2"
	data.raw.ammo["acid-capsule-ammo-2"].order = "3"
	data.raw.ammo["acid-capsule-ammo-3"].subgroup = "dytech-combat-ammo-capsules-3"
	data.raw.ammo["acid-capsule-ammo-3"].order = "3"
end
if data.raw.ammo["firestorm-capsule-ammo-1"] then
	data.raw.ammo["firestorm-capsule-ammo-1"].subgroup = "dytech-combat-ammo-capsules"
	data.raw.ammo["firestorm-capsule-ammo-1"].order = "4"
	data.raw.ammo["firestorm-capsule-ammo-2"].subgroup = "dytech-combat-ammo-capsules-2"
	data.raw.ammo["firestorm-capsule-ammo-2"].order = "4"
	data.raw.ammo["firestorm-capsule-ammo-3"].subgroup = "dytech-combat-ammo-capsules-3"
	data.raw.ammo["firestorm-capsule-ammo-3"].order = "4"
end
if data.raw.ammo["napalm-capsule-ammo-1"] then
	data.raw.ammo["napalm-capsule-ammo-1"].subgroup = "dytech-combat-ammo-capsules"
	data.raw.ammo["napalm-capsule-ammo-1"].order = "5"
	data.raw.ammo["napalm-capsule-ammo-2"].subgroup = "dytech-combat-ammo-capsules-2"
	data.raw.ammo["napalm-capsule-ammo-2"].order = "5"
	data.raw.ammo["napalm-capsule-ammo-3"].subgroup = "dytech-combat-ammo-capsules-3"
	data.raw.ammo["napalm-capsule-ammo-3"].order = "5"
end
if data.raw.ammo["poison-capsule-ammo-1"] then
	data.raw.ammo["poison-capsule-ammo-1"].subgroup = "dytech-combat-ammo-capsules"
	data.raw.ammo["poison-capsule-ammo-1"].order = "6"
	data.raw.ammo["poison-capsule-ammo-2"].subgroup = "dytech-combat-ammo-capsules-2"
	data.raw.ammo["poison-capsule-ammo-2"].order = "6"
	data.raw.ammo["poison-capsule-ammo-3"].subgroup = "dytech-combat-ammo-capsules-3"
	data.raw.ammo["poison-capsule-ammo-3"].order = "6"
end
if data.raw.ammo["radiation-capsule-ammo-1"] then
	data.raw.ammo["radiation-capsule-ammo-1"].subgroup = "dytech-combat-ammo-capsules"
	data.raw.ammo["radiation-capsule-ammo-1"].order = "7"
	data.raw.ammo["radiation-capsule-ammo-2"].subgroup = "dytech-combat-ammo-capsules-2"
	data.raw.ammo["radiation-capsule-ammo-2"].order = "7"
	data.raw.ammo["radiation-capsule-ammo-3"].subgroup = "dytech-combat-ammo-capsules-3"
	data.raw.ammo["radiation-capsule-ammo-3"].order = "7"
end
if data.raw.capsule["marauder-capsule"] then
	data.raw.capsule["marauder-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["marauder-capsule"].order = "4"
	data.raw.capsule["sharpshooter-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["sharpshooter-capsule"].order = "5"
	data.raw.capsule["frenzy-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["frenzy-capsule"].order = "6"
	data.raw.capsule["marauder-turret-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["marauder-turret-capsule"].order = "7"
	data.raw.capsule["sharpshooter-turret-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["sharpshooter-turret-capsule"].order = "8"
	data.raw.capsule["frenzy-turret-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["frenzy-turret-capsule"].order = "9"
	data.raw.capsule["mixed-turret-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["mixed-turret-capsule"].order = "91"
	data.raw.capsule["mixed-capsule"].subgroup = "dytech-combat-robot-capsules"
	data.raw.capsule["mixed-capsule"].order = "92"
end
if data.raw.ammo["advanced-magazines-1"] then
	data.raw.ammo["advanced-magazines-1"].subgroup = "dytech-combat-ammo"
	data.raw.ammo["advanced-magazines-1"].order = "4"
	data.raw.ammo["advanced-magazines-2"].subgroup = "dytech-combat-ammo"
	data.raw.ammo["advanced-magazines-2"].order = "5"
	data.raw.ammo["advanced-magazines-3"].subgroup = "dytech-combat-ammo"
	data.raw.ammo["advanced-magazines-3"].order = "6"
	data.raw.ammo["advanced-magazines-4"].subgroup = "dytech-combat-ammo"
	data.raw.ammo["advanced-magazines-4"].order = "7"
	data.raw.ammo["advanced-magazines-5"].subgroup = "dytech-combat-ammo"
	data.raw.ammo["advanced-magazines-5"].order = "8"
	data.raw.ammo["laser-clip-1"].subgroup = "dytech-combat-ammo-laser"
	data.raw.ammo["laser-clip-1"].order = "1"
	data.raw.ammo["laser-clip-2"].subgroup = "dytech-combat-ammo-laser"
	data.raw.ammo["laser-clip-2"].order = "1"
	data.raw.ammo["laser-clip-3"].subgroup = "dytech-combat-ammo-laser"
	data.raw.ammo["laser-clip-3"].order = "1"
	data.raw.ammo["laser-clip-shotgun-1"].subgroup = "dytech-combat-ammo-laser-shotgun"
	data.raw.ammo["laser-clip-shotgun-1"].order = "1"
	data.raw.ammo["laser-clip-shotgun-2"].subgroup = "dytech-combat-ammo-laser-shotgun"
	data.raw.ammo["laser-clip-shotgun-2"].order = "1"
	data.raw.ammo["laser-clip-shotgun-3"].subgroup = "dytech-combat-ammo-laser-shotgun"
	data.raw.ammo["laser-clip-shotgun-3"].order = "1"
end
if data.raw.ammo["battery-tank"] then
	data.raw.ammo["battery-tank"].subgroup = "dytech-combat-ammo-misc"
	data.raw.ammo["battery-tank"].order = "6"
end
if data.raw.capsule["basic-grenade-2"] then
	data.raw.capsule["basic-grenade-2"].subgroup = "dytech-combat-grenade"
	data.raw.capsule["basic-grenade-2"].order = "3"
	data.raw.capsule["basic-grenade-3"].subgroup = "dytech-combat-grenade"
	data.raw.capsule["basic-grenade-3"].order = "3"
end
if data.raw.gun["sniper"] then
	data.raw.gun["sniper"].subgroup = "dytech-combat-guns"
	data.raw.gun["sniper"].order = "3"
	data.raw.ammo["sniper-magazine"].subgroup = "dytech-combat-ammo"
	data.raw.ammo["sniper-magazine"].order = "3"
end
if data.raw.gun["laser-gun"] then
	data.raw.gun["laser-gun"].subgroup = "dytech-combat-guns"
	data.raw.gun["laser-gun"].order = "4"
end
if data.raw.gun["laser-shotgun"] then
	data.raw.gun["laser-shotgun"].subgroup = "dytech-combat-guns-2"
	data.raw.gun["laser-shotgun"].order = "3"
end

--------------------------[[ Intermediates ]] ------------------

data.raw.tool["science-pack-1"].subgroup = "dytech-intermediates-science"
data.raw.tool["science-pack-1"].order = "0"
data.raw.tool["science-pack-2"].subgroup = "dytech-intermediates-science"
data.raw.tool["science-pack-2"].order = "1"
data.raw.tool["science-pack-3"].subgroup = "dytech-intermediates-science"
data.raw.tool["science-pack-3"].order = "2"
data.raw.tool["alien-science-pack"].subgroup = "dytech-intermediates-science"
data.raw.tool["alien-science-pack"].order = "3"
data.raw.item["landfill"].subgroup = "dytech-intermediates-processing"
data.raw.item["landfill"].order = "0"
data.raw.item["iron-stick"].subgroup = "dytech-intermediates-processing"
data.raw.item["iron-stick"].order = "0"
data.raw.item["wood"].subgroup = "dytech-intermediates-processing"
data.raw.item["wood"].order = "2"
data.raw.item["copper-cable"].subgroup = "dytech-intermediates-wires"
data.raw.item["copper-cable"].order = "1"
data.raw.item["red-wire"].subgroup = "dytech-intermediates-wires"
data.raw.item["red-wire"].order = "11"
data.raw.item["green-wire"].subgroup = "dytech-intermediates-wires"
data.raw.item["green-wire"].order = "12"
data.raw.item["iron-gear-wheel"].subgroup = "dytech-intermediates-gears"
data.raw.item["iron-gear-wheel"].order = "2"
data.raw.item["stone-brick"].subgroup = "dytech-intermediates-processing"
data.raw.item["stone-brick"].order = "3"
data.raw.item["concrete"].subgroup = "dytech-intermediates-processing"
data.raw.item["concrete"].order = "99"
data.raw.item["hazard-concrete"].subgroup = "dytech-intermediates-processing"
data.raw.item["hazard-concrete"].order = "991"
data.raw.item["empty-barrel"].subgroup = "dytech-intermediates-all"
data.raw.item["empty-barrel"].order = "88"
data.raw.recipe["empty-barrel"].subgroup = "dytech-intermediates-all"
data.raw.recipe["empty-barrel"].order = "88"
data.raw.item["engine-unit"].subgroup = "dytech-intermediates-all"
data.raw.item["engine-unit"].order = "2"
data.raw.item["electric-engine-unit"].subgroup = "dytech-intermediates-all"
data.raw.item["electric-engine-unit"].order = "3"
data.raw.item["explosives"].subgroup = "dytech-intermediates-all"
data.raw.item["explosives"].order = "4"
data.raw.item["flying-robot-frame"].subgroup = "dytech-intermediates-all"
data.raw.item["flying-robot-frame"].order = "4"
data.raw["mining-tool"]["iron-axe"].subgroup = "dytech-intermediates-tools"
data.raw["mining-tool"]["iron-axe"].order = "1"
data.raw["mining-tool"]["steel-axe"].subgroup = "dytech-intermediates-tools"
data.raw["mining-tool"]["steel-axe"].order = "2"
data.raw.item["low-density-structure"].subgroup = "dytech-intermediates-all"
data.raw.item["low-density-structure"].order = "9"
data.raw.item["rocket-control-unit"].subgroup = "dytech-intermediates-all"
data.raw.item["rocket-control-unit"].order = "91"
data.raw.item["satellite"].subgroup = "dytech-intermediates-all"
data.raw.item["satellite"].order = "92"
data.raw.item["battery"].subgroup = "dytech-intermediates-battery"
data.raw.item["battery"].order = "0"
data.raw.item["electronic-circuit"].subgroup = "dytech-intermediates-circuitry"
data.raw.item["electronic-circuit"].order = "1"
data.raw.item["advanced-circuit"].subgroup = "dytech-intermediates-circuitry"
data.raw.item["advanced-circuit"].order = "2"
data.raw.item["processing-unit"].subgroup = "dytech-intermediates-circuitry"
data.raw.item["processing-unit"].order = "3"
if data.raw["mining-tool"]["zinc-axe"] then
	data.raw["mining-tool"]["zinc-axe"].subgroup = "dytech-intermediates-tools"
	data.raw["mining-tool"]["zinc-axe"].order = "4"
	data.raw["mining-tool"]["tin-axe"].subgroup = "dytech-intermediates-tools"
	data.raw["mining-tool"]["tin-axe"].order = "3"
	data.raw["mining-tool"]["silver-axe"].subgroup = "dytech-intermediates-tools"
	data.raw["mining-tool"]["silver-axe"].order = "5"
	data.raw["mining-tool"]["lead-axe"].subgroup = "dytech-intermediates-tools"
	data.raw["mining-tool"]["lead-axe"].order = "6"
	data.raw["mining-tool"]["tungsten-axe"].subgroup = "dytech-intermediates-tools"
	data.raw["mining-tool"]["tungsten-axe"].order = "7"
	data.raw["mining-tool"]["cobalt-axe"].subgroup = "dytech-intermediates-tools"
	data.raw["mining-tool"]["cobalt-axe"].order = "8"
end
if data.raw.item["metallurgy-active"] then
	data.raw.item["brick"].subgroup = "dytech-intermediates-processing"
	data.raw.item["brick"].order = "4"
	data.raw.item["aluminium-wire"].subgroup = "dytech-intermediates-wires"
	data.raw.item["aluminium-wire"].order = "2"
	data.raw.item["silver-wire"].subgroup = "dytech-intermediates-wires"
	data.raw.item["silver-wire"].order = "2"
	data.raw.item["gold-wire"].subgroup = "dytech-intermediates-wires"
	data.raw.item["gold-wire"].order = "2"
	data.raw.item["electrum-wire"].subgroup = "dytech-intermediates-wires"
	data.raw.item["electrum-wire"].order = "2"
	data.raw.item["aluminium-gear-wheel"].subgroup = "dytech-intermediates-gears"
	data.raw.item["aluminium-gear-wheel"].order = "4"
	data.raw.item["zinc-gear-wheel"].subgroup = "dytech-intermediates-gears"
	data.raw.item["zinc-gear-wheel"].order = "6"
	data.raw.item["tin-gear-wheel"].subgroup = "dytech-intermediates-gears"
	data.raw.item["tin-gear-wheel"].order = "5"
	data.raw.item["tungsten-gear-wheel"].subgroup = "dytech-intermediates-gears"
	data.raw.item["tungsten-gear-wheel"].order = "7"
	data.raw.item["copper-tungsten-gear-wheel"].subgroup = "dytech-intermediates-gears"
	data.raw.item["copper-tungsten-gear-wheel"].order = "8"
end

--------------------------[[ Machines ]] ------------------

data.raw.item["stone-furnace"].subgroup = "dytech-machines-furnace"
data.raw.item["stone-furnace"].order = "1"
data.raw.item["steel-furnace"].subgroup = "dytech-machines-furnace"
data.raw.item["steel-furnace"].order = "2"
data.raw.item["electric-furnace"].subgroup = "dytech-machines-furnace-electric"
data.raw.item["electric-furnace"].order = "1"
data.raw.item["pumpjack"].subgroup = "dytech-machines-extractors-oil"
data.raw.item["pumpjack"].order = "1"
data.raw.item["assembling-machine-1"].subgroup = "dytech-machines-assembling"
data.raw.item["assembling-machine-1"].order = "1"
data.raw.item["assembling-machine-2"].subgroup = "dytech-machines-assembling"
data.raw.item["assembling-machine-2"].order = "2"
data.raw.item["assembling-machine-3"].subgroup = "dytech-machines-assembling"
data.raw.item["assembling-machine-3"].order = "3"
data.raw.item["beacon"].subgroup = "dytech-machines-beacon"
data.raw.item["beacon"].order = "1"
data.raw.item["oil-refinery"].subgroup = "dytech-machines-oil-processing"
data.raw.item["oil-refinery"].order = "1"
data.raw.item["chemical-plant"].subgroup = "dytech-machines-oil-processing"
data.raw.item["chemical-plant"].order = "4"
data.raw.item["burner-mining-drill"].subgroup = "dytech-machines-extractors"
data.raw.item["burner-mining-drill"].order = "1"
data.raw.item["electric-mining-drill"].subgroup = "dytech-machines-extractors"
data.raw.item["electric-mining-drill"].order = "2"
data.raw.item["rocket-silo"].subgroup = "dytech-machines-misc"
data.raw.item["rocket-silo"].order = "1"
data.raw.item["lab"].subgroup = "dytech-machines-lab"
data.raw.item["lab"].order = "1"














